version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - php8
      - php7
    ports:
      - "8080:80"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data

  php8:
    image: php:8.0-rc-fpm-alpine
    restart: always
    volumes_from:
      - data

  php7:
    image: php:7.4.10-fpm-alpine
    restart: always
    volumes_from:
      - data

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./public_html:/vhosts
      - ./tmp:/tmp

# create network: docker network create xnmp-network
networks:
  default:
    external:
      name: xnmp-network