version: '3.8'

services:
  nginx_xnmp:
    container_name: nginx
    image: nginx:alpine
    links:
      - php8
      - php7
    ports:
      - "8080:80"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data
    networks: 
      - xnmp-network

  php8:
    container_name: php8
    image: php:8.0-rc-fpm-alpine
    volumes_from:
      - data
    networks: 
      - xnmp-network

  php7:
    container_name: php7
    image: php:7.4.10-fpm-alpine
    volumes_from:
      - data
    networks: 
      - xnmp-network

  db_xnmp:
    container_name: db_xnmp
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks: 
      - xnmp-network

  data:
    container_name: data
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./public_html:/vhosts
      - ./tmp:/tmp
    networks: 
      - xnmp-network

# create network: docker network create xnmp-network
networks:
  xnmp-network:
    name: xnmp-network